#!/bin/sh
echo hostname = `hostname`
echo release = `cat /etc/redhat-release`
uptime
echo whoami = `whoami`
echo pwd = `pwd`
echo HALLD_HOME = $HALLD_HOME
echo HALLD_RECON_HOME = $HALLD_RECON_HOME
echo HALLD_SIM_HOME = $HALLD_SIM_HOME
echo latest files:
ls -lt | grep -v 'total ' | head -3
exit
