#!/bin/sh
# By Matt Bickley, August 31, 1994
# Because the repath script is so damned slow, and written idiotically

oldpath=$1
shift

if [ "$1" != "" ] ; then
   STRING=$1
else
   STRING=$PATH
fi

TEMPFILE=/tmp/delpath.$LOGNAME.$$

echo $STRING | tr "[:*]" "[\012*]" > $TEMPFILE

awk -v OLDPATH=$oldpath -f $EPICSROOT/tools/delpath.awk $TEMPFILE | \
 sed 's/:$//'

rm -f $TEMPFILE
