#!/bin/sh
echo ""
echo /w/cache101
df /w/cache101
echo ""
echo /w/cache201
df /w/cache201
echo ""
echo /work/clas/calib
df /work/clas/calib
echo ""
echo /work/clas/disk1
df /work/clas/disk1
echo ""
echo /work/clas/disk2
df /work/clas/disk2
echo ""
echo /work/clas/gsim
df /work/clas/gsim
echo ""
echo /work/clas/physana
df /work/clas/physana
echo ""
echo /work/clas/production
df /work/clas/production
