#!/bin/tcsh
echo ""
echo /w/cache301
df /w/cache301
echo ""
echo /w/cache402
df /w/cache402
echo ""
echo /w/cache501
df /w/cache501
echo ""
echo /w/cache601
df /w/cache601
echo ""
echo /work/clas/calib
df /work/clas/calib
echo ""
echo /work/clas/disk1
df /work/clas/disk1
echo ""
echo /work/clas/disk2
df /work/clas/disk2
echo ""
echo /work/clas/gsim
df /work/clas/gsim
echo ""
echo /work/clas/physana
df /work/clas/physana
echo ""
echo /work/clas/production
df /work/clas/production
