#!/bin/bash
logfile=/tmp/grive_${USER}/grive_`date -Iminutes`.log
lockfile=/tmp/grive_${USER}/grive_`hostname`.lock
mkdir -p /tmp/grive_${USER}
if [ -f $lockfile ]; then
   echo lock file found: $lockfile
   exit 1
fi
date > $lockfile
cd /home/${USER}/google_drive
rm -f $logfile
date > grive_`hostname`.txt
/usr/local/bin/grive > $logfile 2>&1
rm $lockfile
