#!/bin/bash
logfile=/tmp/grive_${USER}/grive_`date -Iminutes`.log
lockfile=/tmp/grive_${USER}/grive_`hostname`.lock
mkdir -p /tmp/grive_${USER}
if [ -f $lockfile ]; then
   echo lock file found: $lockfile
   exit 1
fi
date > $lockfile
cd /home/${USER}/google_drive
rm -f $logfile
date > grive_`hostname`.txt
/usr/local/bin/grive \
    --id 1019311529026-ngooosfm3j7q4l67sdat1l4i9o25r1fq.apps.googleusercontent.com \
    --secret DBHayQg_75W6zKbP-NEK1LaU > $logfile 2>&1
#/usr/local/bin/grive > $logfile 2>&1
rm $lockfile
